chapter_names = [
    'Etymology',
    'Extracts',
    'Loomings',
    'The Carpet-Bag',
    'The Spouter-Inn',
    'The Counterpane',
    'Breakfast',
    'The Street',
    'The Chapel',
    'The Pulpit',
    'The Sermon',
    'A Bosom Friend',
    'Nightgown',
    'Biographical',
    'Wheelbarrow',
    'Nantucket',
    'Chowder',
    'The Ship',
    'The Ramadan',
    'His Mark',
    'The Prophet',
    'All Astir',
    'Going Aboard',
    'Merry Christmas',
    'The Lee Shore',
    'The Advocate',
    'Postscript',
    'Knights And Squires',
    'Knights And Squires',
    'Ahab',
    'Enter Ahab; To Him, Stubb',
    'The Pipe',
    'Queen Mab',
    'Cetology',
    'The Specksynder',
    'The Cabin-Table',
    'The Mast-Head',
    'The Quarter-Deck',
    'Sunset',
    'Dusk',
    'First Night-Watch',
    'Midnight, Forecastle',
    'Moby Dick',
    'The Whiteness of the Whale',
    'Hark!',
    'The Chart',
    'The Affidavit',
    'Surmises',
    'The Mat-Maker',
    'The First Lowering',
    'The Hyena',
    'Ahab\'s Boat and Crew. Fedallah',
    'The Spirit-Spout',
    'The Albatross',
    'The Gam',
    'The Town-Ho\'s Story',
    'Of the Monstrous Pictures of Whales',
    'Of the Less Erroneous Pictures of Whales, and the True Pictures of Whaling Scenes',
    'Of Whales in Paint; in Teeth; in Wood; in Sheet-Iron; in Stone; in Mountains; in Stars',
    'Brit',
    'Squid',
    'The Line',
    'Stubb Kills A Whale',
    'The Dart',
    'The Crotch',
    'Stubb\'s Supper',
    'The Whale as a Dish',
    'The Shark Massacre',
    'Cutting In',
    'The Blanket',
    'The Funeral',
    'The Sphynx',
    'The Jeroboam\'s Story',
    'The Monkey Rope',
    'Stubb and Flask Kill a Right Whale; and Then Have a Talk Over Him',
    'The Sperm Whale\'s Head—Contrasted View',
    'The Right Whale\'s Head—Contrasted View',
    'The Battering-Ram',
    'The Great Heidelburgh Tun',
    'Cistern and Buckets',
    'The Prairie',
    'The Nut',
    'The Pequod Meets the Virgin',
    'The Honor and Glory of Whaling',
    'Jonah Historically Regarded',
    'Pitchpoling',
    'The Fountain',
    'The Tail',
    'The Grand Armada',
    'Schools and Schoolmasters',
    'Fast-Fish and Loose-Fish',
    'Heads or Tails',
    'The Pequod Meets the Rose-Bud',
    'Ambergris',
    'The Castaway',
    'A Squeeze of the Hand',
    'The Cassock',
    'The Try-Works',
    'The Lamp',
    'Stowing Down and Clearing Up',
    'The Doubloon',
    'Leg and Arm: The Pequod, of Nantucket, Meets the Samuel Enderby, Of London',
    'The Decanter',
    'A Bower in the Arsacides',
    'Measurement of the Whale\'s Skeleton',
    'The Fossil Whale',
    'Does the Whale\'s Magnitude Diminish?—Will he Perish?',
    'Ahab\'s Leg',
    'The Carpenter',
    'Ahab and the Carpenter',
    'Ahab and Starbuck in the Cabin',
    'Queequeg in his Coffin',
    'The Pacific',
    'The Blacksmith',
    'The Forge',
    'The Gilder',
    'The Pequod Meets The Bachelor',
    'The Dying Whale',
    'The Whale Watch',
    'The Quadrant',
    'The Candles',
    'The Deck Towards the End of the First Night Watch',
    'Midnight—The Forecastle Bulwarks',
    'Midnight Aloft—Thunder and Lightning',
    'The Musket',
    'The Needle',
    'The Log and Line',
    'The Life-Buoy',
    'The Deck',
    'The Pequod Meets the Rachel',
    'The Cabin',
    'The Hat',
    'The Pequod Meets the Delight',
    'The Symphony',
    'The Chase—First Day',
    'The Chase—Second Day',
    'The Chase—Third Day',
    'Epilogue'
]